a = input('Type anything: ')
print('The primitive type of this value is', type(a))
print('Spaces only? ', a.isspace())
print('Is it a number? ', a.isnumeric())
print('Is it an alphabeit? ', a.isalpha())
print('Is it an alpha num? ', a.isalnum())
print('Is it a capital letter? ', a.isupper())
print('Is it a lower case letter? ', a.islower())
print('Is capitalized? ', a.istitle())